export const ACTION_CATEGORIES = [
    "Sports",
    "Finance",
    "Data",
    "Entertainment",
    "Travel",
    "Location",
    "Science",
    "Food",
    "Transportation",
    "Visual Recognition",
    "Tools",
    "Text Analysis",
    "Weather",
    "Gaming",
    "SMS",
    "Health and Fitness",
    "Payments",
]