name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Update
        uses: appleboy/ssh-action@v0.1.2
        with:
         host: ${{secrets.SSH_HOST}}
         key: ${{secrets.SSH_KEY}}
         username: ${{secrets.SSH_USERNAME}}

         script: |
           cd ../var/www/supermind/supermind-admin
           git pull origin master
           echo 'pull successful'
           
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
      - name: Restart Nginx
        run: systemctl daemon-reload
      - name: Restart Service
        run: systemctl restart admin.service
      
